export default {
    suffix: [
        'png',
        'doc',
        'docx',
        'xls',
        'xlsx',
        'pdf',
        'rar',
        'ppt',
        'jpg',
        'mp3',
        'mp4',
        'file',
    ],
    columns1: [
        {
            type: 'selection',
            width: 30,
            align: 'center',
        },
        {
            title: '文件名称',
            key: 'Name',
            slot: 'Name',
            // minWidth: 150,
        },
        {
            title: ' ',
            key: 'action',
            slot: 'action',
            align: 'left',
            width: 150,
        },
        {
            title: '更新时间',
            key: 'AddTime',
            slot: 'AddTime',
            sortable: true,
            align: 'center',
            width: 150,
        },
        {
            title: '大小',
            key: 'fileSize',
            slot: 'fileSize',
            align: 'center',
            width: 80,
        },
    ],
    columns2: [
        {
            type: 'selection',
            width: 30,
        },
        {
            title: '文件名称',
            key: 'Name',
            slot: 'Name',
        },
        {
            title: ' ',
            key: 'action',
            slot: 'action',
            align: 'left',
            width: 100,
        },
        {
            title: '更新时间',
            key: 'AddTime',
            slot: 'AddTime',
            sortable: true,
            align: 'center',
            width: 80,
        },
        {
            title: '大小',
            key: 'fileSize',
            slot: 'fileSize',
            align: 'center',
            width: 60,
        },
    ],
};
